# Generated by Django 4.2.1 on 2023-05-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Cat',
        ),
    ]
