# Generated by Django 4.2.1 on 2023-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_rename_categories_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
    ]
